### ISSUE TITLE
Upload Test Report from CI

### ISSUE THREAD

**Issue by bearbob** [bearbob/cyoa_engine#16]
After the CI has finished, we want to be able to look into the Test Report. The Report needs to be uploaded as artifact.

```
  - uses: actions/upload-artifact@v3
    with:
      name: Package
      path: build/libs

```
